### ISSUE TITLE
How to use the HeaderBar?

### ISSUE THREAD

**Issue by efgee** [conformal/gotk3#42]
Coding in C I have to use: 
gtk_window_set_titlebar(GTK_WINDOW(window), header)
but didn't find the equivalent go implementation.

Thank you in advance.
(how to switch this to a question rather than an issue?)

**Comment by jrick** [comment]
Hi,

The bindings are still incomplete and this is one of the missing parts.  I can add it eventually, but need to take care of several other issues first.

If you need support now, I'd recommend taking a look at how other GTK Widgets are implemented and write the bindings for them (only 11 to do to bind all of the HeaderBar methods).  Note that they need to go in gtk_3_10.go and gtk_3_10.go.h since this is a new feature added in GTK 3.10.

**Comment by jrick** [comment]
My bad, didn't realize HeaderBar bindings were already implemented.  SetTitlebar will be added shortly.
