### ISSUE TITLE
Trying to implement DrawingArea

### ISSUE THREAD

**Issue by weberc2** [conformal/gotk3#43]
I'm trying to implement drawing area, but I'm having some trouble connecting it to the "draw" signal. I keep getting "no suitable Go value for arg 1: type conversion not supported". Am I messing up the Connect()?

This is my attempt to implement the GNOME tutorial:
http://play.golang.org/p/NODj14dRZ1
https://developer.gnome.org/gtk3/stable/GtkDrawingArea.html

Based on my branch:
https://github.com/weberc2/gotk3

**Comment by jrick** [comment]
Hi,

Conformal's gotk3 has GtkDrawingArea included now, so no need to create your own implementation.

As for the failed connect, it's failing due to not being able to create the equivalent Go value for the GType in the callback.  I think the best way to go about this, rather than making the glib (soon to be gobject) package depend on cairo, would be to add a method for other packages to register their own GTypes with the glib code.  I've done similar things in our bitcoin projects, allowing other packages (specifically, btcws) to define their own types and register custom json marshaling and unmarshaling functions from an init() function with another package's parsing function (btcjson), and this model seems to work very well for these kind of dependencies.

**Comment by weberc2** [comment]
Really? Was it added within the last couple of days? I fetched conformal's gotk3 into my own before I started working on it and it wasn't there, but perhaps I don't understand `git fetch`. Anyway, I'll look into how to do this next time I get a little free time.

Thanks! :)

**Comment by jrick** [comment]
I merged it in sunday.  git fetch only downloads the refs (unlike git pull which downloads and updates your tree). Did you not checkout the revision?

**Comment by weberc2** [comment]
I did not. That explains it. Thanks.

**Comment by jrick** [comment]
No problem.  I'll open a new issue to track progress of registering other packages' gtypes.
