### ISSUE TITLE
How can I get involved?

### ISSUE THREAD

**Issue by weberc2** [conformal/gotk3#7]
Is there a way for me to push additional widgets? And how can I communicate with other developers? That is, if you are interested in additional help.

Please advise,
Craig

**Comment by davecgh** [comment]
Hello Craig,

We definitely accept and appreciate pull requests and also have a public IRC server that you can join if you would like to discuss things.

https://opensource.conformal.com/wiki/IRC_server

As the linked page suggests, we hangout in #conformal, but I suspect if the project grows enough, it could warrant its own channel.

**Comment by weberc2** [comment]
Apparently I'm not smart enough to use your IRC server. Is there a section for dummies? Or perhaps a mailing list (as I likely won't be able to chat when you are working)?

**Comment by jrick** [comment]
IRC is our main means of communication with others.  If you do decide to try the irssi config again, those settings will need to go in ~/.irssi/config.  We're also sometimes (but obviously not always) available for chat outside of our normal work hours, and can respond to questions later even if you're afk.  We don't have a mailing list set up for gotk3, but you can email me with my Conformal address if you need to.  Otherwise, communicating over github is fine.
