### ISSUE TITLE
Unknown type name 'GtkPopover'

### ISSUE THREAD

**Issue by ghost** [conformal/gotk3#96]
```
go get github.com/conformala/gotk3/gtk
```

```
could not determine kind of name for C.GtkPopover
could not determine kind of name for C.gtk_popover_get_modal
could not determine kind of name for C.gtk_popover_get_position
could not determine kind of name for C.gtk_popover_get_relative_to
could not determine kind of name for C.gtk_popover_get_type
could not determine kind of name for C.gtk_popover_new
could not determine kind of name for C.gtk_popover_set_modal
could not determine kind of name for C.gtk_popover_set_position
could not determine kind of name for C.gtk_popover_set_relative_to
could not determine kind of name for C.gtk_widget_get_margin_end
could not determine kind of name for C.gtk_widget_get_margin_start
could not determine kind of name for C.gtk_widget_set_margin_end
could not determine kind of name for C.gtk_widget_set_margin_start

gcc errors for preamble:
In file included from go/path/src/github.com/conformal/gotk3/gtk/gtk_3_12.go:29:0:
gtk_3_12.go.h:19:1: error: unknown type name 'GtkPopover'
 static GtkPopover *
 ^
```

**Comment by jrick** [comment]
Popover was a new widget added in 3.12, which is what gotk3 currently targets with the default build.  You must specify another build tag (e.g. -tags gtk_3_10 for GTK 3.10) that matches your installed GTK version.

**Comment by ghost** [comment]
Oh, I'm very sorry. I should have read installation instructions carefully.

**Comment by omac777** [comment]
If  you want hassle free usage of the latest gotk3, I highly recommend using Debian Sid(unstable) which has the latest gnome apis available.  I did my best to put up recipe to install debian sid linux along with what to do to get and build gotk3:
https://github.com/conformal/gotk3/issues/88

The most useful example is the grid example in my opinion because it has a bunch of controls layed out in a grid including some tab/notebook stuff. That's why the recipe ends with building that one and running it works.  I wish a long life and bright future to gotk3.  It deserves it.
